apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: thanos
  namespace: monitoring
  labels:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/part-of: observability
spec:
  jobLabel: app.kubernetes.io/name
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values: [thanos-query, thanos-query-frontend, thanos-store, thanos-compactor]
  endpoints:
    - port: http
      interval: 30s
