{{- if .Values.externalSecret.enabled }}
apiVersion: {{ .Values.externalSecret.apiVersion | default "external-secrets.io/v1" }}
kind: ExternalSecret
metadata:
  name: {{ include "microservice.secretName" . }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    kind: {{ .Values.externalSecret.storeRef.kind | default "ClusterSecretStore" }}
    name: {{ .Values.externalSecret.storeRef.name | default "vault-backend" }}
  target:
    name: {{ include "microservice.secretName" . }}
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        labels:
          {{- include "microservice.labels" . | nindent 10 }}
  dataFrom:
    - extract:
        key: {{ include "microservice.vaultPath" . }}
  {{- with .Values.externalSecret.data }}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
